### PR TITLE
Interface Creation

### PR DESCRIPTION
**Pull request by jyoung8711**
I've used this toolkit across several projects, but due to complications from a couple of customers, needed to transition instead to a .NET based API, rather than the native LabVIEW one (separate toolkit, not published yet).  Rather than sorting through all projects and replacing each VI, I thought it would be easier to convert the original class into an "interface" class, and encapsulate the original functionality into a concrete sub-class.... my .NET API could then be encapsulated in a similar manner.

So then in projects that use this, I only need to adjust things in one place: the initialization function to call the initialization VI from the new Sub-class.  The changes should be "non-breaking" other than perhaps with the initialize VI.

I don't know whether this would be useful to pull into the main repo, so thought I'd create a pull request and see.
I do not have LV2013 installed, so before I went through the effort to install/back save (currently LV2018 32-bit), I thought I'd reach out and see if you are interested in integrating these changes.

I also fully intend on publishing the .NET API a bit later (which is a much more complete/flexible HTTP Client), however, how the form I publish that in will also depend on whether you're interested in integrating these changes, since the changes are non-destructive (other than the initialize), figured it was worth reaching out :)

- Made the original REST Client an interface class
- Copied the original REST class to "REST Client_JKI"
- Adjusted files to match new architecture
- No functionality change should have occurred
- likely "Create REST Client.vi" will break because I removed some inputs
- SHOULD call "Create JKI Rest Client" to maintain original functionality
- Adjusted scope of several VIs to make them more broadly accessible
- Currently updated to LV2018 32-bit (Still back compatible w/2013, but don't have that installed)

### CODE REVIEW

**Comment by jimkring** [comment]
Hi @jyoung8711. Yes, I think we need to do this since the NI HTTP Client VIs are not always the best once's for users.  Are you still working on this at all?  Would you still be willing to help out with this effort?

**Comment by jyoung8711** [comment]
@jimkring -- We aren't "actively" working on this right now, but I have been using my modified version of this toolkit since the original post. I'm definitely amenable to dusting this off to collaborate on an update.

The strategy I took was to make the original class an abstract class, and moving all of the "interesting stuff" into a sub class. this kept things from breaking except for the initialization VI.... which was intentional so that it would force users to look at it and add in the new "create" VI for the concrete version they cared about.

I then extended this with a class based on the .NET HTTP Client -- which was needed on ourside for more complex Proxy Server support

I took a look at the post by Chris in your link, and had similar problems as him with some of the useful stuff being encapsulated in privately scoped VIs.

The caveats I have right now are :

- Our current version was written in LV 2018, so to match support for the current version, it would need to be back-saved and validated for 2013 (I think)
- I don't have any unit tests for the original JKI toolkit, so I can't validate functionality of that library in the new version (I mostly use the .NET concrete class for our use cases right now).

Let me know how you'd like to proceed.

**Comment by jyoung8711** [comment]
Sounds good.  I'll standby!

**Comment by jimkring** [comment]
Hi @jyoung8711.

there has been some work on this. See PR #30

**Comment by jyoung8711** [comment]
Hey @jimkring -- Thanks for the ping.

I've been keeping an eye on the project, and saw that there was work being done.  I had not seen the new issue/proposal, but since that basically just happened over the weekend, not too surprising.

Our .NET API is located (publicly) here: https://github.com/Viviota/LabVIEW-HttpClient-NET 
I don't think I have a release/VIPM posted, but the latest push should have a library that directly references this one.
My memory is aside from the interface translation, the only thing I had to change was a adjusting the scope of the a couple of VIs... but it's been 3 years since I did that work, and my memory is a little lacking.

I will pull down the current version of this from #30 and figure out how close the interface is what I needed in this fork, and can do a little testing on my side.

Looking forward to this change, as I'm currently maintaining my own fork of this project to maintain the .NET interface (which I need to handle some proxy server resolution that I really don't want to rewrite myself).  Once the interfaced version is pushed to public, I'll plan on pushing the .NET VIPM package out as well.

**Comment by jimkring** [comment]
@jyoung8711 fantastic! Looking forward to your feedback.

**Comment by jyoung8711** [comment]
@jimkring -- I had a bit to review the new and generally I think that the new interface will do as needed.  I'll respond with additional comments/feedback in those threads, as it'll make more sense in context.

Thanks for pulling me into this conversation!

(If you'd like to close out this pull request as "rejected" I think that will be fine, as the other requests will sufficiently address what was done here)

**Pull request closed without merging**
