### PR TITLE
Patch Method - NI Advanced HTTP Client support - Assert IsFile fix

### LINKED ISSUE #25: Assert_IsFile.vi hangs when passed large json body requests that are not files
vi.lib\addons\_JKI.lib\REST Client\classes\REST Client\Assert_IsFile.vi
image

The vi above takes in the body of a request to determine if it is a file path. The problem is that "String to Path" takes a very long time to execute for bodies that are large. I have a put request hat has over 1 million characters in it (json string publishing to a web page).  AND for reasons I don't understand, the String to Path returns the massive JSON string as a path!

Even worse, the "File or Folder Exists" hangs when the very large path is passed to it. 

So I'm going to have to revert to the previous release of the rest api. 

Recommended solutions
1. get string length. if larger than the OS max path length, this is not a path. (not sure if this will work for both windows and mac). 

In any event, an alternate algorithm is needed to determine if this string is a path or not.

### PR DESCRIPTION
**Pull request by francois-normandin**
[Feature #24] Rebuilt against NI Advanced HTTP Client
[Fix #25] Assert_isFile fixed
[Feature #27] Updated the client to use NI Advanced HTTP Client and added the PATCH method

[jki_lib_rest_client-2.1.0.33.vip.zip](https://github.com/vipm-io/HTTP-REST-Client/files/12414945/jki_lib_rest_client-2.1.0.33.vip.zip)

I made the NI Advanced HTTP Client an internal dependency. A rebuild is needed to depend on the community-available package instead.

### CODE REVIEW

**Comment by ChrisCilinoGC** [comment]
@francois-normandin I think your pull request is broken. When I install your zip file it is linking against the adv http client that points to the following dll:
C:\Program Files (x86)\National Instruments\LabVIEW 2020\vi.lib\NI\Advanced HTTP Client\lvwebclient_32.dll
even though I had installed version 2.1.0.33 to 64 bit labview. Oh wow... and for whatever reasons the rest api vis are located at: C:\Program Files\National Instruments\LabVIEW 2020\vi.lib\addons\_JKI.lib\_REST Client_internal_deps\
 
So stuff is majorly broken.

**Comment by francois-normandin** [comment]
@ChrisCilinoGC the location in the internal dependencies is expected because I deleted the dependency on the external package (easier to install offline when not dependent on external packages... Although with two DLLs as part of the package, it seems to break!).

I had not tested it on a 64-bit LabVIEW installation and judging from what you're describing, I'll have to rebuild using external dependencies, otherwise VIPM will build only with the dll being used during the build process, which was lv32-bit when I did it. Pretty sure this is the only change required to resolve it.

Good catch.

**Comment by francois-normandin** [comment]
@ChrisCilinoGC Can you try this one?

[jki_lib_rest_client-2.1.0.34.zip](https://github.com/vipm-io/HTTP-REST-Client/files/13539809/jki_lib_rest_client-2.1.0.34.zip)

**Comment by ChrisCilino** [comment]
Ship it! Thank you @francois-normandin !!!

**Comment by RogelioPonce** [comment]
Hi, I have an issue with the dll's or something like that, I'm working with labview 2025 and 2026, but I need to install the runtime 2024 to works

I don't know if is possible to fix or when you have the same problem, the solution is installing the runtime 2024 and you can use your executable fine.

**Pull request merged**
